import { useCallback, useEffect, useRef, useState } from 'react';
import { isConfigured, supabase } from '../lib/supabase';

/** "Today's board" — design turn 7, /home.
 *
 *  A board is the one competitive surface on a site that otherwise refuses to
 *  compare learners, so the design hedges it carefully and so does this:
 *  opt-in, default off, no prize, and leaving erases you from past boards too.
 *
 *  Why a board is allowed to be open while /doubts and /members are shut:
 *  every value here is machine-made. The handle is generated by the database
 *  (0008), the level is arithmetic, the counts are counts. There is no field a
 *  learner can type into, so there is nothing to moderate and nothing a child
 *  can accidentally publish about themselves. Rooms carry writing; this does
 *  not.
 */

type Row = {
  rank: number; handle: string; level: number;
  lessons: number; reviews: number; points: number; is_me: boolean;
};
type Scope = 'today' | 'week';

export default function Board() {
  const [scope, setScope] = useState<Scope>('today');
  const [rows, setRows] = useState<Row[] | null>(null);
  const [optedIn, setOptedIn] = useState<boolean | null>(null);
  const [signedIn, setSignedIn] = useState<boolean | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  /* Guards against an out-of-order response. Clicking "This week" then
     "Today" leaves two calls in flight, and if the slower first one resolves
     last its rows land under the Today tab — weekly totals labelled Today,
     with nothing to indicate anything is wrong. Only the newest call is
     allowed to write. */
  const latest = useRef(0);

  const refresh = useCallback(async (s: Scope) => {
    const ticket = ++latest.current;
    const fresh = () => ticket === latest.current;
    if (!isConfigured) { setSignedIn(false); return; }
    const sb = supabase();
    const { data: { user } } = await sb.auth.getUser();
    if (!fresh()) return;
    setSignedIn(!!user);
    if (!user) return;

    const [{ data: prof }, { data: board, error: e }] = await Promise.all([
      sb.from('profiles').select('leaderboard_opt_in').eq('id', user.id).single(),
      sb.rpc('daily_board', { p_scope: s, p_limit: 10 }),
    ]);
    if (!fresh()) return;
    setOptedIn(prof?.leaderboard_opt_in === true);
    if (e) { setError('The board could not be loaded just now.'); setRows([]); return; }
    setError(null);
    setRows((board as Row[]) ?? []);
  }, []);

  useEffect(() => { refresh(scope); }, [scope, refresh]);

  async function toggle(on: boolean) {
    setBusy(true);
    try {
      const { error: e } = await supabase().rpc('set_leaderboard_opt_in', { p_on: on });
      if (e) throw e;
      await refresh(scope);
    } catch {
      setError('That did not save. Your setting is unchanged.');
    } finally { setBusy(false); }
  }

  /* Signed out there is no board to show and no opt-in to offer, so the panel
     says what it is instead of rendering an empty table. */
  if (signedIn === false) {
    return (
      <section aria-labelledby="board-h" className="card" style={{ marginBlock: 'var(--sp-6)' }}>
        <h2 id="board-h" style={{ marginTop: 0, fontSize: 'var(--fs-400)' }}>Today's board</h2>
        <p style={{ color: 'var(--c-ink-soft)' }}>
          An optional daily board sits here for signed-in learners. It is off until you
          turn it on, and your progress works exactly the same either way.
        </p>
        <a className="btn btn--ghost" href="/account">Sign in</a>
      </section>
    );
  }
  if (signedIn === null) return null;

  const tab = (s: Scope) => ({
    padding: 'var(--sp-2) var(--sp-4)', borderRadius: 999, cursor: 'pointer',
    border: '1px solid ' + (scope === s ? 'var(--c-border-strong)' : 'transparent'),
    background: scope === s ? 'var(--c-surface-2)' : 'transparent',
    color: scope === s ? 'var(--c-ink)' : 'var(--c-ink-soft)',
    fontWeight: scope === s ? 600 : 400,
  });
  const num: React.CSSProperties = { textAlign: 'right', fontVariantNumeric: 'tabular-nums' };
  const td: React.CSSProperties = { padding: 'var(--sp-3) var(--sp-2)', borderTop: '1px solid var(--c-border)' };

  return (
    <section aria-labelledby="board-h" className="card" style={{ marginBlock: 'var(--sp-6)' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline',
        gap: 'var(--sp-3)', flexWrap: 'wrap' }}>
        <div>
          <h2 id="board-h" style={{ margin: 0, fontSize: 'var(--fs-400)' }}>Today's board</h2>
          <p style={{ margin: 'var(--sp-1) 0 0', color: 'var(--c-ink-faint)', fontSize: 'var(--fs-100)' }}>
            Resets at midnight, your time zone
          </p>
        </div>
        <div role="tablist" aria-label="Board period" style={{ display: 'flex', gap: 'var(--sp-1)' }}>
          {(['today', 'week'] as Scope[]).map((s) => (
            <button key={s} role="tab" aria-selected={scope === s} style={tab(s)}
              onClick={() => setScope(s)}>
              {s === 'today' ? 'Today' : 'This week'}
            </button>
          ))}
        </div>
      </div>

      {error && <p role="alert" style={{ color: 'var(--c-alert)' }}>{error}</p>}

      {rows === null ? (
        <p role="status" style={{ color: 'var(--c-ink-soft)', marginTop: 'var(--sp-4)' }}>Loading…</p>
      ) : rows.length === 0 ? (
        /* No invented rows. The design's sample board shows five names because
           a mockup needs to show something; shipping those names would be a
           fabrication, and a learner who joined and saw strangers who do not
           exist would be right to distrust every other number on this page. */
        <p style={{ color: 'var(--c-ink-soft)', marginTop: 'var(--sp-4)' }}>
          {optedIn
            ? 'Nobody has scored yet ' + (scope === 'today' ? 'today' : 'this week') + '. Finish a lesson and you will be first.'
            : 'Nobody is on the board yet. It fills up as learners opt in.'}
        </p>
      ) : (
        <div style={{ overflowX: 'auto', marginTop: 'var(--sp-4)' }}>
          <table style={{ width: '100%', borderCollapse: 'collapse', minWidth: '28rem' }}>
            <thead>
              <tr style={{ fontSize: 'var(--fs-100)', color: 'var(--c-ink-faint)', textAlign: 'left' }}>
                <th scope="col" style={{ padding: 'var(--sp-2)' }}>#</th>
                <th scope="col" style={{ padding: 'var(--sp-2)' }}>Member</th>
                <th scope="col" style={{ padding: 'var(--sp-2)' }}>Level</th>
                <th scope="col" style={{ padding: 'var(--sp-2)' }}>
                  {scope === 'today' ? 'Today' : 'This week'}
                </th>
                <th scope="col" style={{ padding: 'var(--sp-2)', ...num }}>Points</th>
              </tr>
            </thead>
            <tbody>
              {rows.map((r) => (
                <tr key={r.handle} style={r.is_me ? { background: 'var(--c-surface-2)' } : undefined}>
                  <td style={{ ...td, ...num, color: 'var(--c-ink-faint)' }}>{r.rank}</td>
                  <td style={td}>
                    <span style={{ display: 'inline-flex', alignItems: 'center', gap: 'var(--sp-2)' }}>
                      {/* The "avatar" is the handle's initials. A real image
                          upload would be a file a child could put their face
                          in, which the safeguarding policy rules out. */}
                      <span aria-hidden="true" style={{
                        width: 26, height: 26, borderRadius: 999, flex: '0 0 auto',
                        background: 'var(--c-surface-2)', border: '1px solid var(--c-border)',
                        display: 'grid', placeItems: 'center',
                        fontSize: '0.7rem', color: 'var(--c-ink-soft)' }}>
                        {r.handle.split('-').map((p) => p[0]).slice(0, 2).join('')}
                      </span>
                      <span translate="no">{r.handle}</span>
                      {r.is_me && <strong style={{ fontSize: 'var(--fs-100)', color: 'var(--c-progress)' }}>you</strong>}
                    </span>
                  </td>
                  <td style={{ ...td, color: 'var(--c-ink-soft)' }}>Level {r.level}</td>
                  <td style={{ ...td, color: 'var(--c-ink-soft)' }}>
                    {r.lessons} lesson{r.lessons === 1 ? '' : 's'} · {r.reviews} review{r.reviews === 1 ? '' : 's'}
                  </td>
                  <td style={{ ...td, ...num }}><strong>{r.points}</strong></td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}

      {optedIn === false && (
        <div style={{ marginTop: 'var(--sp-4)', paddingTop: 'var(--sp-4)',
          borderTop: '1px solid var(--c-border)' }}>
          <p style={{ margin: '0 0 var(--sp-1)' }}><strong>You are not on the board</strong></p>
          <p style={{ margin: '0 0 var(--sp-3)', color: 'var(--c-ink-soft)' }}>
            Your progress is private by default. Nothing above knows you exist.
          </p>
          <button className="btn" disabled={busy} onClick={() => toggle(true)}>
            {busy ? 'Joining…' : 'Join the board'}
          </button>
        </div>
      )}

      {optedIn === true && (
        <div style={{ marginTop: 'var(--sp-4)', paddingTop: 'var(--sp-4)',
          borderTop: '1px solid var(--c-border)' }}>
          <p style={{ margin: '0 0 var(--sp-3)', color: 'var(--c-ink-soft)' }}>
            You are on the board. Leaving removes your past entries too.
          </p>
          <button className="btn btn--ghost" disabled={busy} onClick={() => toggle(false)}>
            {busy ? 'Leaving…' : 'Leave the board'}
          </button>
        </div>
      )}

    </section>
  );
}

/** "How the board works" — its own section in the design, below the continue
 *  card rather than inside the board. Kept separate here for that reason: the
 *  rules are worth reading BEFORE joining, and burying them inside the panel
 *  they govern is how consent copy gets skipped. */
export function BoardExplainer() {
  return (
    <section aria-labelledby="boardhow-h" style={{ marginBlock: 'var(--sp-6)' }}>
      <h2 id="boardhow-h" style={{ fontSize: 'var(--fs-300)' }}>How the board works</h2>
      <ul style={{ color: 'var(--c-ink-soft)', paddingInlineStart: '1.2em',
        display: 'grid', gap: 'var(--sp-2)' }}>
        <li>Opt in and out whenever you like. Leaving removes your past entries too.</li>
        <li>Only a display name, an avatar and a level show. Never your real name, email or location.</li>
        <li>
          Your display name is generated for you and cannot be edited. That is deliberate:
          it means nobody can publish their own name here, which matters because some
          learners are under 18. <a href="/safeguarding">Child safety →</a>
        </li>
        <li>Points come from lessons, quizzes and review cards — not from time spent on the site.</li>
        <li>There is no prize. It is a nudge, and it is meant to be ignorable.</li>
      </ul>
    </section>
  );
}
